# Generated by Django 4.1.7 on 2023-03-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
