"""agregue tabla tareas

Revision ID: 426946a5161b
Revises: be94251951da
Create Date: 2023-03-13 10:32:31.302167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426946a5161b'
down_revision = 'be94251951da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'REALIZADOSE', 'REALIZADA', 'CANCELADA', name='estadotareaenum'), nullable=True),
    sa.Column('Usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tareas')
    # ### end Alembic commands ###
