# Generated by Django 4.1.7 on 2023-04-03 19:58

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_cree_tabla_usuario'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('sexo', models.TextField(choices=[('HEMBRA', 'HEMBRA'), ('MACHO', 'MACHO')])),
                ('fechaNacimiento', models.DateField(db_column='Fecha_nacimiento')),
                ('alergias', models.TextField()),
                ('foto', cloudinary.models.CloudinaryField(max_length=255, verbose_name='foto')),
                ('cliente', models.ForeignKey(db_column='clinete_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mascota',
            },
        ),
    ]
